version: "3.4"


services:
# https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook
  jupyter-spark:
    image: 127.0.0.1:5001/jupyter-spark
    build: ../jupyter/
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/work:/home/jovyan/work 
    networks:
      - datastore
    deploy:
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: "1"
          memory: 4G
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure


networks:
  datastore:


